package com.chartiq.finsemble.example;

import javax.swing.*;
import java.awt.*;

public class JavaExample2 {
    private JPanel mainPanel;
    private JButton sendSymbolButton;
    private JTextField textField1;
    private JComboBox componentComboBox;
    private JButton launchComponentButton;
    private JCheckBox dockCheckBox;
    private JCheckBox group1CheckBox;
    private JCheckBox group2CheckBox;
    private JCheckBox group3CheckBox;
    private JCheckBox group4CheckBox;
    private JCheckBox group5CheckBox;
    private JCheckBox group6CheckBox;



    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new GridBagLayout());
        sendSymbolButton = new JButton();
        sendSymbolButton.setText("Connect");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.BOTH;
        mainPanel.add(sendSymbolButton, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }
}
